### ISSUE TITLE
ClojureScript based React-Native App - Embed Videos

### ISSUE THREAD

**Issue by tessy2728** [cljsrn/cljsrn-org#19]
I am new to ClojureScript. I would like to embed video (Youtube) to the hybrid mobile app using ClojureScript and React Native. I have tried to implement react-native-video and react-native-youtube plugins in ClojureScript for achieving this. But, both of these didn't work. I don't know whether there is something wrong with referring to the library or not.

Using react-native-video:

(def Video (js/require "react-native-video")) 
(def video-view (r/adapt-react-class (oget Video "default")))

The component reference:

[video-view {:style {:position "absolute"
                            :top 0
                            :bottom 0
                            :left 0
                            :right 0}
                      :source {:uri "https://www.youtube.com/watch?v=M8Fn8SfXw3M"}}]

There is no error. But, the component is not rendered on the page.

I am using **lein** for compiling ClojureScript **Re-Natal** for building this ClojureScript-based React Native app.

Is there anything wrong with the above code? Anyone, please help?

**Comment by mfikes** [comment]
Hi @tessy2728. This repo is for the http://cljsrn.org website source. For help with using ClojureScript with React Native, I'd suggest checking out the `#cljsrn` channel in the [Clojurians](http://clojurians.net/) Slack.
