### ISSUE TITLE
www is not resolving

### ISSUE THREAD

**Issue by dotemacs** [cljsrn/cljsrn-org#32]
Typed `cljsrn.org`, my browser "helpfully completed" the "www." prefix and took me to https://www.cljsrn.org, which just timed out.

Looking at:

```
$ dig cljsrn.org +short
192.155.92.62
$ dig www.cljsrn.org +short
```

`www` is not configured. 

Maybe it can point to the same host as the apex domain and then it can redirect to to the apex domain?

**Comment by dotemacs** [comment]
I guess a little change occurred since now 

```
$ dig www.cljsrn.org +short
192.155.92.62
```

When you go to that URL you just get the nginx welcome page.

Maybe a redirection to the www-less in nginx config?

```
server {
    server_name  www.cljsrn.org;
    rewrite ^(.*) http://cljsrn.org$1 permanent;
}
```

**Comment by mfikes** [comment]
@dotemacs Thanks for following up! Yes, I had added the DNS but I need to fix the nginx config.

**Comment by mfikes** [comment]
@dotemacs Thanks, that configuration appears to have worked!
